Dynamic memory allocation
mamboelrey/PFMCPP_Project4 pull request #2
Opened 2022-08-02 19:52 UTC by mamboelrey

Added code to create 3 new UDTs and relevant dynamic memory allocation techniques

2022-08-02 23:24 UTC, matkatmusic requested changes
1) please put the star and & next to the type name when you're declaring variables and return it types. 
2) you skipped this instructions:
```
 4) write add/subtract/divide/multiply member functions for each type that take your 3 UDTs
        These are in addition to your member functions that take primitives
        for example, IntType::divide(const DoubleType& dt);
        These functions should return the result of calling the function that takes the primitive.
```
specifically:
```
These functions should return the result of calling the function that takes the primitive.
```
3) you don't need to use the `this` keyword.

I am not going to mark every spot that needs revising.  Essentially every added function needs fixing, though.
- [x] revise

2022-08-03 00:28 UTC, mamboelrey commented
Made required changes

2022-08-03 00:31 UTC, mamboelrey reviewed
Made the required changes

2022-08-03 05:21 UTC, matkatmusic requested changes
D.R.Y.

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*it.value);
your `IntType::divide(int)` already has this std::cout message in it.
You don't need to duplicate the message here
all you need to do is call `return divide(*it.value);` in this function.
- [ ] revise

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*ft.value);
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +}
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
>      }
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*it.value);
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*dt.value);
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*ft.value);
- [ ] revise, see above comments

2022-08-03 05:21 UTC, matkatmusic commented on main.cpp
> +    return divide(*dt.value);
- [ ] revise, see above comments

2022-08-05 03:47 UTC, matkatmusic approved these changes

2022-08-05 03:48 UTC, merged